service: scoring-api

frameworkVersion: '2 || 3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  region: us-west-2
  runtime: python3.9
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 15
    vpc:
      securityGroupIds:
        - sg-0e496cc75edb4a2d3
      subnetIds:
        - subnet-05887b7ea439c47ed 
        - subnet-09331182cd588ae80
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
